title: kvn11
email: kevin.2.romero@uconn.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: none
github_username:  Kvn11

# Build settings
theme: jekyll-shell-theme
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - about.md
  - htb/htb.md
  - ctf.md
  - projects.md
font-size: large
